services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: supersecret
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: '0'
      - key: TZ
        value: Asia/Ho_Chi_Minh
