FROM n8nio/n8n

ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=supersecret
ENV TZ=Asia/Ho_Chi_Minh
ENV N8N_PORT=5678
ENV N8N_HOST=0.0.0.0

EXPOSE 5678
